language: android
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

script: ./gradlew build test --continue